# Generated by Django 4.2.18 on 2025-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
