# Generated by Django 4.2.18 on 2025-02-02 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_alter_faq_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question',
            new_name='question_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='language',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_bn',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_hi',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
