# Generated by Django 4.2.18 on 2025-02-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_rename_answer_faq_answer_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer_en',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_en',
            new_name='question',
        ),
    ]
